export const CHANGE_SEARCH_INPUT = "CHANGE_SEARCH_INPUT";
export const SHOW_CHECKSPELLING_DIALOG = "SHOW_CHECKSPELLING_DIALOG";
export const SEARCH_SKILL = "SEARCH_SKILL";
export const HIDE_CHECKSPELLING_DIALOG = "HIDE_CHECKSPELLING_DIALOG";
export const COPY_CORRECTED_TEXT = "COPY_CORRECTED_TEXT";

